# Redes neuronales Feed Forward
**Inteligencia artificial** <br>
**Hoja de trabajo no. 2** <br>
Diego Sevilla <br>
17238

### Se importan librerias

In [3]:
import numpy as np # para operaciones con matrices y vectores
import pandas as pd 
from scipy import optimize as op
from numpy import genfromtxt # para obetener los datos
from matplotlib import pyplot as plt # para graficar
from matplotlib import image as mpimg # para graficar

from AlgoritmoRN import *
import time

Datasets adquiridos de: https://www.kaggle.com/zalando-research/fashionmnist#fashion-mnist_test.csv <br>
### Se leen los data_sets: 

In [4]:
##train_data = genfromtxt('fashion-mnist_train.csv', delimiter=',')
train_data = pd.read_csv('fashion-mnist_train.csv')
print(train_data)

       label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          2       0       0       0       0       0       0       0       0   
1          9       0       0       0       0       0       0       0       0   
2          6       0       0       0       0       0       0       0       5   
3          0       0       0       0       1       2       0       0       0   
4          3       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995      9       0       0       0       0       0       0       0       0   
59996      1       0       0       0       0       0       0       0       0   
59997      8       0       0       0       0       0       0       0       0   
59998      8       0       0       0       0       0       0       0       0   
59999      7       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel775  pixel776 

In [5]:
##test_data = genfromtxt('fashion-mnist_test.csv', delimiter=',')
test_data = pd.read_csv('fashion-mnist_test.csv')
print(test_data)

      label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0         0       0       0       0       0       0       0       0       9   
1         1       0       0       0       0       0       0       0       0   
2         2       0       0       0       0       0       0      14      53   
3         2       0       0       0       0       0       0       0       0   
4         3       0       0       0       0       0       0       0       0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995      0       0       0       0       0       0       0       0       0   
9996      6       0       0       0       0       0       0       0       0   
9997      8       0       0       0       0       0       0       0       0   
9998      8       0       1       3       0       0       0       0       0   
9999      1       0       0       0       0       0       0       0     140   

      pixel9  ...  pixel775  pixel776  pixel777  pi

### Organizacion de los datos

**Normalizacion de los datos**

In [6]:
NORMALIZADOR = 1000.0

#### Vector X

In [7]:
x_tr = train_data.iloc[:, 1:] / NORMALIZADOR
m_tr, n_tr = x_tr.shape

In [8]:
print( x_tr.shape )

(60000, 784)


In [9]:
x_t = test_data.iloc[:, 1:] / NORMALIZADOR
m_t, n_t = x_t.shape

In [10]:
print( x_t.shape )

(10000, 784)


In [11]:
X = np.vstack((
    x_tr,
    x_t
))
m, n = X.shape

In [12]:
print( X.shape )

(70000, 784)


In [13]:
print(X)

[[0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 ...
 [0.    0.    0.    ... 0.    0.001 0.   ]
 [0.    0.001 0.003 ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]


#### Vector Y

In [14]:
y_tr = np.asarray(train_data.iloc[:, 0])
y_tr = y_tr.reshape(m_tr,1)

y_t = np.asarray(test_data.iloc[:, 0])
y_t = y_t.reshape(m_t,1)

## 
y = np.vstack((
    y_tr,
    y_t
))

y = y.reshape(m, 1)

# Matriz de categorizacion
Y = (y == np.array(range(10))).astype(int)

In [15]:
print(y)

[[2]
 [9]
 [6]
 ...
 [8]
 [8]
 [1]]


In [16]:
print(Y)

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]]


### RED NEURONAL

**Definicion de entradas de red neuronal, obtencion de shapes de theta y aplanacion de matrices**

In [17]:
# Estructura de la red neuronal
NETWORK_ARCHITECTURE = np.array([
    n,
    130,
    10
])

# Funcion para los shapes de las thetas
theta_shapes = np.hstack((
    NETWORK_ARCHITECTURE[1:].reshape(len(NETWORK_ARCHITECTURE) - 1, 1),
    (NETWORK_ARCHITECTURE[:-1] + 1).reshape(len(NETWORK_ARCHITECTURE) - 1, 1)
))

# Convierte la matriz a un array de thetas
flat_thetas = flatten_list_of_arrays([
    np.random.rand(*theta_shape)
    for theta_shape in theta_shapes
])

**Proceso de entramiento y optimizacion**

In [18]:
# Optimizacion para encontrar thetas
print("\n Optimizando ..... \n")
result = op.minimize(
    fun = cost_function,
    x0 = flat_thetas,
    args = (theta_shapes, X, Y),
    method = 'L-BFGS-B',
    jac = back_propagation,
    options = {'disp': True, 'maxiter': 3000}
)
print("\n Fin de optimizacion ..... \n")


 Optimizando ..... 



C:\Users\Diego Sevilla\Documents\Repositorios\7mo Semestre\Inteligencia Artificial\Redes-Neuronales\RNFeedForward\AlgoritmoRN.py:37: RuntimeWarning: divide by zero encountered in log
  return -(Y * np.log(a[-1]) + (1 - Y) * np.log(1 - a[-1])).sum() / len(X)
C:\Users\Diego Sevilla\Documents\Repositorios\7mo Semestre\Inteligencia Artificial\Redes-Neuronales\RNFeedForward\AlgoritmoRN.py:37: RuntimeWarning: invalid value encountered in multiply
  return -(Y * np.log(a[-1]) + (1 - Y) * np.log(1 - a[-1])).sum() / len(X)



 Fin de optimizacion ..... 



In [ ]:
# Se guarda el resultado de thetas optimizadas
np.savetxt('thetas_op.txt', result.x)