# Redes neuronales de tipo Feed Forward
**Inteligencia artificial** <br>
**Hoja de trabajo no. 2** <br>
Diego Sevilla <br>
17238

### Se importan librerias

In [1]:
import numpy as np # para operaciones con matrices y vectores
import pandas as pd 
from scipy import optimize as op
from numpy import genfromtxt # para obetener los datos
from matplotlib import pyplot as plt # para graficar
from matplotlib import image as mpimg # para las imagenes

from AlgoritmoRN import *
import time

Datasets adquiridos de: https://www.kaggle.com/zalando-research/fashionmnist#fashion-mnist_test.csv <br>
### Se cargan los data_sets: 

In [2]:
##train_data = genfromtxt('fashion-mnist_train.csv', delimiter=',')
train_data = pd.read_csv('fashion-mnist_train.csv')
train_data

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          2       0       0       0       0       0       0       0       0   
1          9       0       0       0       0       0       0       0       0   
2          6       0       0       0       0       0       0       0       5   
3          0       0       0       0       1       2       0       0       0   
4          3       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995      9       0       0       0       0       0       0       0       0   
59996      1       0       0       0       0       0       0       0       0   
59997      8       0       0       0       0       0       0       0       0   
59998      8       0       0       0       0       0       0       0       0   
59999      7       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0        30        43   
3           0  ...         3         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
59995       0  ...         0         0         0         0         0   
59996       0  ...        73         0         0         0         0   
59997       0  ...       160       162       163       135        94   
59998       0  ...         0         0         0         0         0   
59999       0  ...         0         0         0         0         0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             1         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
59995         0         0         0         0         0  
59996         0         0         0         0         0  
59997         0         0         0         0         0  
59998         0         0         0         0         0  
59999         0         0         0         0         0  

[60000 rows x 785 columns]

In [3]:
##test_data = genfromtxt('fashion-mnist_test.csv', delimiter=',')
test_data = pd.read_csv('fashion-mnist_test.csv')
test_data

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0         0       0       0       0       0       0       0       0       9   
1         1       0       0       0       0       0       0       0       0   
2         2       0       0       0       0       0       0      14      53   
3         2       0       0       0       0       0       0       0       0   
4         3       0       0       0       0       0       0       0       0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995      0       0       0       0       0       0       0       0       0   
9996      6       0       0       0       0       0       0       0       0   
9997      8       0       0       0       0       0       0       0       0   
9998      8       0       1       3       0       0       0       0       0   
9999      1       0       0       0       0       0       0       0     140   

      pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          8  ...       103        87        56         0         0         0   
1          0  ...        34         0         0         0         0         0   
2         99  ...         0         0         0         0        63        53   
3          0  ...       137       126       140         0       133       224   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
9995       0  ...        32        23        14        20         0         0   
9996       0  ...         0         0         0         2        52        23   
9997       0  ...       175       172       172       182       199       222   
9998       0  ...         0         0         0         0         0         1   
9999     119  ...       111        95        75        44         1         0   

      pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0  
1            0         0         0         0  
2           31         0         0         0  
3          222        56         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
9995         1         0         0         0  
9996        28         0         0         0  
9997        42         0         1         0  
9998         0         0         0         0  
9999         0         0         0         0  

[10000 rows x 785 columns]

### Organizacion de los datos

**Normalizacion de los datos**

In [4]:
NORMALIZADOR = 1000.0

#### Vector X

In [5]:
x_tr = train_data.iloc[:, 1:] / NORMALIZADOR
rows_tr, cols_tr = x_tr.shape

In [6]:
print( x_tr.shape )

(60000, 784)


In [7]:
x_tr

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
1         0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
2         0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.005     0.0   
3         0.0     0.0     0.0   0.001   0.002     0.0     0.0   0.000     0.0   
4         0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995     0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
59996     0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
59997     0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
59998     0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   
59999     0.0     0.0     0.0   0.000   0.000     0.0     0.0   0.000     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0          0.0  ...     0.000     0.000     0.000     0.000     0.000   
1          0.0  ...     0.000     0.000     0.000     0.000     0.000   
2          0.0  ...     0.000     0.000     0.000     0.030     0.043   
3          0.0  ...     0.003     0.000     0.000     0.000     0.000   
4          0.0  ...     0.000     0.000     0.000     0.000     0.000   
...        ...  ...       ...       ...       ...       ...       ...   
59995      0.0  ...     0.000     0.000     0.000     0.000     0.000   
59996      0.0  ...     0.073     0.000     0.000     0.000     0.000   
59997      0.0  ...     0.160     0.162     0.163     0.135     0.094   
59998      0.0  ...     0.000     0.000     0.000     0.000     0.000   
59999      0.0  ...     0.000     0.000     0.000     0.000     0.000   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0         0.000       0.0       0.0       0.0       0.0  
1         0.000       0.0       0.0       0.0       0.0  
2         0.000       0.0       0.0       0.0       0.0  
3         0.001       0.0       0.0       0.0       0.0  
4         0.000       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
59995     0.000       0.0       0.0       0.0       0.0  
59996     0.000       0.0       0.0       0.0       0.0  
59997     0.000       0.0       0.0       0.0       0.0  
59998     0.000       0.0       0.0       0.0       0.0  
59999     0.000       0.0       0.0       0.0       0.0  

[60000 rows x 784 columns]

In [8]:
x_t = test_data.iloc[:, 1:] / NORMALIZADOR
rows_t, cols_t = x_t.shape

In [9]:
print( x_t.shape )

(10000, 784)


In [10]:
x_t

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0        0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.009   0.008   
1        0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.000   0.000   
2        0.0   0.000   0.000     0.0     0.0     0.0   0.014   0.053   0.099   
3        0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.000   0.000   
4        0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.000   0.000   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995     0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.000   0.000   
9996     0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.000   0.000   
9997     0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.000   0.000   
9998     0.0   0.001   0.003     0.0     0.0     0.0   0.000   0.000   0.000   
9999     0.0   0.000   0.000     0.0     0.0     0.0   0.000   0.140   0.119   

      pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0.000  ...     0.103     0.087     0.056     0.000     0.000   
1       0.000  ...     0.034     0.000     0.000     0.000     0.000   
2       0.017  ...     0.000     0.000     0.000     0.000     0.063   
3       0.161  ...     0.137     0.126     0.140     0.000     0.133   
4       0.000  ...     0.000     0.000     0.000     0.000     0.000   
...       ...  ...       ...       ...       ...       ...       ...   
9995    0.037  ...     0.032     0.023     0.014     0.020     0.000   
9996    0.000  ...     0.000     0.000     0.000     0.002     0.052   
9997    0.000  ...     0.175     0.172     0.172     0.182     0.199   
9998    0.000  ...     0.000     0.000     0.000     0.000     0.000   
9999    0.103  ...     0.111     0.095     0.075     0.044     0.001   

      pixel780  pixel781  pixel782  pixel783  pixel784  
0        0.000     0.000     0.000     0.000       0.0  
1        0.000     0.000     0.000     0.000       0.0  
2        0.053     0.031     0.000     0.000       0.0  
3        0.224     0.222     0.056     0.000       0.0  
4        0.000     0.000     0.000     0.000       0.0  
...        ...       ...       ...       ...       ...  
9995     0.000     0.001     0.000     0.000       0.0  
9996     0.023     0.028     0.000     0.000       0.0  
9997     0.222     0.042     0.000     0.001       0.0  
9998     0.001     0.000     0.000     0.000       0.0  
9999     0.000     0.000     0.000     0.000       0.0  

[10000 rows x 784 columns]

In [11]:
X = np.vstack((
    x_tr,
    x_t
))
rows, cols = X.shape

In [12]:
print( X.shape )

(70000, 784)


In [13]:
print(X)

[[0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 ...
 [0.    0.    0.    ... 0.    0.001 0.   ]
 [0.    0.001 0.003 ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]


In [14]:
print(np.asarray(train_data.iloc[:, 0]))

[2 9 6 ... 8 8 7]


#### Vector Y

In [15]:
y_tr = np.asarray(train_data.iloc[:, 0])
print(y_tr)

[2 9 6 ... 8 8 7]


In [16]:
y_tr = y_tr.reshape(rows_tr,1)
print(y_tr)

[[2]
 [9]
 [6]
 ...
 [8]
 [8]
 [7]]


In [17]:
#Se repiten pasos para los datos de prueba
y_t = np.asarray(test_data.iloc[:, 0])
y_t = y_t.reshape(rows_t,1)

In [18]:
y = np.vstack((
    y_tr,
    y_t
))
print(y)

[[2]
 [9]
 [6]
 ...
 [8]
 [8]
 [1]]


In [19]:
y = y.reshape(rows, 1)
print(y)

[[2]
 [9]
 [6]
 ...
 [8]
 [8]
 [1]]


In [20]:
# Matriz de categorizacion
Y = (y == np.array(range(10))).astype(int)

In [21]:
print(y)

[[2]
 [9]
 [6]
 ...
 [8]
 [8]
 [1]]


In [22]:
print(Y)

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]]


### RED NEURONAL

**Definicion de entradas de red neuronal, obtencion de shapes de theta y aplanacion de matrices**

In [ ]:
# Estructura de la red neuronal
NETWORK_ARCHITECTURE = np.array([
    cols,
    130,
    10
])
NETWORK_ARCHITECTURE

In [ ]:
# Funcion para los shapes de las thetas
theta_shapes = np.hstack((
    NETWORK_ARCHITECTURE[1:].reshape(len(NETWORK_ARCHITECTURE) - 1, 1),
    (NETWORK_ARCHITECTURE[:-1] + 1).reshape(len(NETWORK_ARCHITECTURE) - 1, 1)
))
theta_shapes

In [23]:
# Convierte la matriz a un array de thetas
flat_thetas = flatten_list_of_arrays([
    np.random.rand(*theta_shape)
    for theta_shape in theta_shapes
])
flat_thetas

**Proceso de entramiento y optimizacion**

In [ ]:
# Optimizacion para encontrar thetas
print("\n Optimizando ..... \n")
result = op.minimize(
    fun = cost_function,
    x0 = flat_thetas,
    args = (theta_shapes, X, Y),
    method = 'L-BFGS-B',
    jac = back_propagation,
    options = {'disp': True, 'maxiter': 3000}
)
print("\n Fin de optimizacion ..... \n")


 Optimizando ..... 



C:\Users\Diego Sevilla\Documents\Repositorios\7mo Semestre\Inteligencia Artificial\Redes-Neuronales\RNFeedForward\AlgoritmoRN.py:37: RuntimeWarning: divide by zero encountered in log
  return -(Y * np.log(a[-1]) + (1 - Y) * np.log(1 - a[-1])).sum() / len(X)
C:\Users\Diego Sevilla\Documents\Repositorios\7mo Semestre\Inteligencia Artificial\Redes-Neuronales\RNFeedForward\AlgoritmoRN.py:37: RuntimeWarning: invalid value encountered in multiply
  return -(Y * np.log(a[-1]) + (1 - Y) * np.log(1 - a[-1])).sum() / len(X)


Se guarda el resultado de las thetas optimizadas en un archivo de texto...

In [ ]:
np.savetxt('thetas_op.txt', result.x)

Referencias: <br>
- https://dzone.com/articles/the-very-basic-introduction-to-feed-forward-neural
- https://mlfromscratch.com/neural-networks-explained/#/ <br>
- https://www.youtube.com/watch?v=tIeHLnjs5U8 <br>
**Clases en linea con Samuel.